### ISSUE TITLE
Admin panel for Account Service and Real-Time Toxic Text Detection

### ISSUE THREAD

**Issue by MarkHmnv** [UpTalent/AccountService#25]
### Description
The intent of the admin panel is to allow administrators to manage users in the system effectively. The panel will provide admin with capabilities to alter the status of users and notify them via email about the changes. The statuses could be Active, On Moderation, or Blocked.

### Tasks

- [x] Create ModerationStatus enum with the following statuses: ACTIVE, ON_MODERATION, BLOCKED
- [x] Add endpoint for blocking users with email notification
- [x] Add endpoint for unblocking users with email notification
- [x] Add endpoint to retrieve all users with status ON_MODERATION or BLOCKED
- [x] Create entity Report with ManyToOne connection to Account
- [x] Add endpoints to report user(set status to ON_MODERATION)
- [x] Configure PerspectiveApi client for toxic text detection
- [x] Send users to moderation if their name or about me contains toxic text
- [x] Connect with WebSocket. Whenever a user is transferred to the status ON_MODERATION, the server sends a message through this endpoint to the admin panel.
