### ISSUE TITLE
Write Tests for AccountService

### ISSUE THREAD

**Issue by MarkHmnv** [UpTalent/AccountService#29]
### Description
Write Tests for AccountService

### Tasks
- AccountService + AccountController:
- [ ] Save User successfully 
- [ ] Log in successfully 
- [ ] Log in when account is deleted
- [ ] Log in with incorrect password
- [ ] Update User profile successfully 
- [ ] Update User profile with incorrect data
- [ ] Change User password successfully
- [ ] Change User password with wrong old password
- [ ] Send email to restore password successfully 
- [ ] Send email to restore password when User is not found 
- [ ] Restore password with token successfully 
- [ ] Restore password with not found token
- [ ] Delete User account 
- [ ] Restore deleted account with token successfully 
- [ ] Restore deleted account with not found token
- TalentService + TalentController:
- [ ] Get all talents successfully 
- SponsorService + SponsorController:
- [ ] Get all sponsors successfully 
- AdminService + AdminController:
- [x] Get all users with moderation status
- [x] Block user successfully
- [x] Block user with status BLOCKED
- [x] Unblock user successfully 
- [x] Unblock user with status ACTIVE or ON_MODERATION
- [x] Activate user successfully 
- [x] Activate user with status ACTIVE
- SkillService + SkillController:
- [x] Get all skills successfully 
- [x] Update Talent skills successfully 
- [x] Update Talent skills when talent is not found
- [x] Update Talent skills when skill is not found
- ReportService + TalentController + SponsorController
- [x] Report Talent successfully 
- [x] Report Talent that is not found
- [x] Check toxicity and report Talent
- [x] Check toxicity and don't report Talent
- [x] Report Sponsor successfully 
- [x] Report Sponsor that is not found
- [x] Check toxicity and report Sponsor
- [x] Check toxicity and don't report Sponsor
