### ISSUE TITLE
Basic CRUD Operations for Users

### ISSUE THREAD

**Issue by MarkHmnv** [UpTalent/AccountService#6]
### Description
Users(Talent and Sponsor) can view, update, delete own profile. The aim is to extract and replicate essential functionality related to user management from the monolith app into the AccountService, allowing for a more modular and scalable architecture.

### Tasks
- [x] User can view own profile
- [x] User can update own profile
- [x] User can delete own profile
- [x] Guest can view a list of Talents
