### ISSUE TITLE
Soft Delete Pattern and Redis Cache for Deleted Users 

### ISSUE THREAD

**Issue by MarkHmnv** [UpTalent/AccountService#8]
### Description
When a user account is deleted, it will be marked as "temporary deleted" and stored in Redis cache for 7 days. Additionally, the NotificationService will be responsible for sending a notification email to the deleted user, containing a restoration link. Users can click on the restoration link within the 7-day period to restore their account. After 7 days, the Redis cache will be cleared, permanently removing the soft deleted user accounts.

### Tasks
- [x] Configure Redis
- [x] Integrate Redis cache functionality to store soft deleted user accounts
- [x] Store soft deleted user accounts in Redis cache for a duration of 7 days.
- [x] Implement sending an email notification to the soft deleted user, containing a restoration link.
- [x] After the 7-day period, clear the Redis cache to remove all soft deleted user accounts that have exceeded the restoration timeframe.
